name: Lint

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-mypy-ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.16"
          enable-cache: true
      - name: Install packages
        shell: bash
        run: uv sync --all-extras
      - name: lint code mypy
        shell: bash
        run:  uv run mypy src
      - name: lint check code format
        shell: bash
        run: uv run ruff check src
      - name: lint format code
        shell: bash
        run: uv run ruff format src --check
